apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2
kind: Deployment
metadata:
  name: alluxio-monitor-group
  namespace: ava
spec:
  selector:
    matchLabels:
      app: alluxio-monitor-group
  replicas: 1 # tells deployment to run 2 pods matching the template
  template:
    metadata:
      labels:
        app: alluxio-monitor-group
    spec:
      hostNetwork: true
      imagePullSecrets:
        - name: atlab-images
      containers:
      - name: alluxio-exporter
        imagePullPolicy: Always
        image: reg-xs.qiniu.io/atlab/alluxio-exporter:group-v1.2
        volumeMounts:
        - name: config-volume
          mountPath: /conf
      volumes:
      - name: config-volume
        configMap:
          name: alluxio-exporter-config
